// src/components/Gallery.svelte
<script>
  import { fade } from "svelte/transition";
  export let images = [];

  let selectedImage = null;

  function openModal(image) {
    selectedImage = image;
    document.body.style.overflow = "hidden";
  }

  function closeModal() {
    selectedImage = null;
    document.body.style.overflow = "auto";
  }
</script>

<section id="gallery" class="py-20 bg-white">
  <div class="container mx-auto px-6">
    <div class="text-center mb-16">
      <h2 class="text-4xl font-bold text-gray-900 mb-4">Our Masterpieces</h2>
      <div class="w-24 h-1 bg-[var(--primary)] mx-auto rounded-full"></div>
      <p class="mt-4 text-xl text-gray-600 max-w-2xl mx-auto">
        Explore our portfolio of custom outdoor kitchens, designed to transform
        backyards into culinary paradises.
      </p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {#each images as image, i}
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <div
          class="group relative overflow-hidden rounded-xl shadow-lg cursor-pointer aspect-[4/3]"
          on:click={() => openModal(image)}
        >
          <img
            src={image.src}
            alt={`Gallery Image ${i + 1}`}
            class="w-full h-full object-cover transform group-hover:scale-110 transition-transform duration-700"
          />
          <div
            class="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center"
          >
            <span
              class="text-white font-semibold text-lg border border-white px-6 py-2 rounded-full hover:bg-white hover:text-black transition-colors"
            >
              View Project
            </span>
          </div>
        </div>
      {/each}
    </div>
  </div>

  {#if selectedImage}
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div
      class="fixed inset-0 z-50 bg-black/95 flex items-center justify-center p-4"
      on:click={closeModal}
      transition:fade
    >
      <button
        class="absolute top-6 right-6 text-white hover:text-[var(--primary)] transition-colors"
        on:click={closeModal}
      >
        <svg
          class="w-10 h-10"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          ></path>
        </svg>
      </button>

      <img
        src={selectedImage.src}
        alt="Gallery Fullscreen"
        class="max-w-full max-h-[90vh] rounded-lg shadow-2xl"
        on:click|stopPropagation
      />
    </div>
  {/if}
</section>

// src/components/gallery.tsx
import { Button } from "@/components/ui/button";
import React from "react";

interface GalleryProps {
  images: {
    src: string;
    alt: string;
    width: number;
    height: number;
  }[];
}

export default function Gallery({ images }: GalleryProps) {
  return (
    <div className='container'>
      <div className='text-center mb-12'>
        <h2 className='text-3xl md:text-4xl font-bold mb-4'>Our Work</h2>
        <div className='w-20 h-1 bg-primary mx-auto mb-6'></div>
        <p className='max-w-2xl mx-auto text-muted-foreground'>
          Browse through our portfolio of stunning outdoor kitchen projects
          we've completed for satisfied customers.
        </p>
      </div>

      <div className='grid md:grid-cols-2 lg:grid-cols-3 gap-6'>
        {images.map((image, index) => (
          <div
            key={index}
            className='relative group overflow-hidden rounded-lg'
          >
            <div className='aspect-[4/3] relative'>
              <img
                src={image.src}
                alt={image.alt}
                width={image.width}
                height={image.height}
                className='object-cover w-full h-full transition-transform duration-300 group-hover:scale-105'
              />
            </div>
            <div className='absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center'>
              <p className='text-white text-center px-4'>{image.alt}</p>
            </div>
          </div>
        ))}
      </div>

      <div className='mt-12 text-center'>
        <Button asChild size='lg' className='bg-primary hover:bg-primary/90'>
          <a href='#contact'>Get Your Dream Kitchen</a>
        </Button>
      </div>
    </div>
  );
}
