// src/components/Hero.svelte
<script>
  export let heroImage;
</script>

<section
  class="relative h-screen flex items-center justify-center overflow-hidden"
>
  <!-- Background Image with Overlay -->
  <div class="absolute inset-0 z-0">
    <img
      src={heroImage.src}
      alt="Outdoor Kitchen"
      class="w-full h-full object-cover"
    />
    <div
      class="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/60"
    ></div>
  </div>

  <!-- Content -->
  <div class="relative z-10 text-center px-6 max-w-4xl mx-auto">
    <h1
      class="text-5xl md:text-7xl font-bold text-white mb-6 leading-tight drop-shadow-lg"
    >
      Elevate Your <span class="text-orange-500">Outdoor</span> Lifestyle
    </h1>
    <p
      class="text-xl md:text-2xl text-gray-200 mb-10 max-w-2xl mx-auto drop-shadow-md"
    >
      Premium custom outdoor kitchens designed for entertaining and built to
      last.
    </p>
    <div class="flex flex-col md:flex-row gap-4 justify-center">
      <a
        href="#contact"
        class="bg-orange-600 text-white px-8 py-4 rounded-full text-lg font-bold hover:bg-orange-700 transition-all shadow-xl hover:shadow-2xl transform hover:-translate-y-1"
      >
        Start Your Project
      </a>
      <a
        href="#gallery"
        class="bg-white/10 backdrop-blur-sm border-2 border-white/30 text-white px-8 py-4 rounded-full text-lg font-bold hover:bg-white/20 transition-all shadow-lg hover:shadow-xl"
      >
        View Our Work
      </a>
    </div>
  </div>

  <!-- Scroll Indicator -->
  <div
    class="absolute bottom-10 left-1/2 transform -translate-x-1/2 animate-bounce"
  >
    <svg
      class="w-8 h-8 text-white/80"
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M19 14l-7 7m0 0l-7-7m7 7V3"
      ></path>
    </svg>
  </div>
</section>

// src/components/hero.tsx
import type React from "react";

import { Button } from "@/components/ui/button";
import { ChevronDown } from "lucide-react";

export default function Hero(props: { children: React.ReactNode }) {
  const scrollToSection = (
    e: React.MouseEvent<HTMLAnchorElement>,
    href: string
  ) => {
    e.preventDefault();
    const element = document.querySelector(href);
    if (element) {
      window.scrollTo({
        top: element.getBoundingClientRect().top + window.scrollY - 80,
        behavior: "smooth",
      });
    }
  };

  return (
    <div className='relative min-h-screen flex items-center'>
      {/* Background Image */}
      <div className='absolute inset-0 z-0'>{props.children}</div>

      <div className='container relative z-10 pt-20'>
        <div className='max-w-3xl text-white'>
          <h1 className='text-4xl md:text-5xl lg:text-6xl font-bold mb-6'>
            Transform Your Backyard Into An Outdoor Culinary Paradise
          </h1>
          <p className='text-lg md:text-xl mb-8 text-white/90'>
            Custom outdoor kitchen design and installation by Wassi's - bringing
            quality craftsmanship to your home since 1986.
          </p>
          <div className='flex flex-col sm:flex-row gap-4'>
            <Button
              asChild
              size='lg'
              className='bg-primary hover:bg-primary/90 text-white'
            >
              <a
                href='#contact'
                onClick={(e) => scrollToSection(e, "#contact")}
              >
                Get a Free Quote
              </a>
            </Button>
            <Button
              asChild
              size='lg'
              variant='outline'
              className='bg-white/10 backdrop-blur-sm text-white border-white hover:bg-white/20'
            >
              <a
                href='#services'
                onClick={(e) => scrollToSection(e, "#services")}
              >
                Explore Our Services
              </a>
            </Button>
          </div>
        </div>
      </div>

      {/* Scroll Down Indicator */}
      <div className='absolute bottom-8 left-1/2 transform -translate-x-1/2 text-white animate-bounce'>
        <a
          href='#about'
          onClick={(e) => scrollToSection(e, "#about")}
          className='flex flex-col items-center'
        >
          <span className='text-sm mb-2'>Scroll Down</span>
          <ChevronDown className='h-6 w-6' />
        </a>
      </div>
    </div>
  );
}
