// src/components/navbar.tsx
import type React from "react";

import { useState, useEffect } from "react";
import { Menu } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

const navLinks = [
  { name: "Home", href: "#home" },
  { name: "About", href: "#about" },
  { name: "Services", href: "#services" },
  { name: "Gallery", href: "#gallery" },
  { name: "Testimonials", href: "#testimonials" },
  { name: "Contact", href: "#contact" },
];

export default function Navbar(props: { children: React.ReactNode }) {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 10) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToSection = (
    e: React.MouseEvent<HTMLAnchorElement>,
    href: string
  ) => {
    e.preventDefault();
    const element = document.querySelector(href);
    if (element) {
      window.scrollTo({
        top: element.getBoundingClientRect().top + window.scrollY - 80,
        behavior: "smooth",
      });
    }
    // Close the mobile menu when a link is clicked
    setIsOpen(false);
  };

  return (
    <header
      className={cn(
        "fixed top-0 left-0 right-0 z-50 transition-all duration-300",
        isScrolled
          ? "bg-white dark:bg-background/80 backdrop-blur-sm shadow-md py-2"
          : "bg-transparent py-4"
      )}
    >
      <div className='container flex items-center justify-between'>
        <a href='#home' className='relative z-10'>
          {props.children}
        </a>

        {/* Desktop Navigation */}
        <nav className='hidden lg:flex items-center space-x-8'>
          {navLinks.map((link) => (
            <a
              key={link.name}
              href={link.href}
              onClick={(e) => scrollToSection(e, link.href)}
              className={cn(
                "text-base font-medium transition-colors hover:text-primary",
                link.name === "Contact" ? "hidden" : ""
              )}
            >
              {link.name}
            </a>
          ))}
          <Button asChild className='bg-primary hover:bg-primary/90 text-white'>
            <a href='#contact' onClick={(e) => scrollToSection(e, "#contact")}>
              Contact Us
            </a>
          </Button>
        </nav>

        {/* Mobile Navigation */}
        <Sheet open={isOpen} onOpenChange={setIsOpen}>
          <SheetTrigger asChild>
            <Button variant='ghost' size='icon' className='lg:hidden'>
              <Menu className='h-6 w-6' />
              <span className='sr-only'>Toggle menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side='right'>
            <nav className='flex flex-col space-y-6 mt-12'>
              {navLinks.map((link) => (
                <a
                  key={link.name}
                  href={link.href}
                  onClick={(e) => scrollToSection(e, link.href)}
                  className='text-lg font-medium transition-colors hover:text-primary'
                >
                  {link.name}
                </a>
              ))}
              <Button
                asChild
                className='bg-primary hover:bg-primary/90 text-white w-full mt-4'
              >
                <a
                  href='#contact'
                  onClick={(e) => scrollToSection(e, "#contact")}
                >
                  Contact Us
                </a>
              </Button>
            </nav>
          </SheetContent>
        </Sheet>
      </div>
    </header>
  );
}

// src/components/Navbar.svelte
<script>
  import { onMount } from "svelte";

  export let logo;

  let isScrolled = false;

  onMount(() => {
    const handleScroll = () => {
      isScrolled = window.scrollY > 20;
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  });
</script>

<nav
  class={`fixed w-full z-50 transition-all duration-300 ${isScrolled ? "bg-white/90 backdrop-blur-md shadow-md py-2" : "bg-gradient-to-b from-black/50 to-transparent py-4"}`}
>
  <div class="container mx-auto px-6 flex justify-between items-center">
    <a href="/" class="flex items-center gap-2">
      <img
        src={logo.src}
        alt="Wassis' Outdoor Kitchens"
        class="h-12 w-auto drop-shadow-md"
      />
    </a>

    <div class="hidden md:flex items-center gap-8">
      <a
        href="#gallery"
        class={`font-medium transition-colors drop-shadow-md ${isScrolled ? "text-gray-800 hover:text-[var(--primary)]" : "text-white hover:text-[var(--primary)]"}`}
        >Gallery</a
      >
      <a
        href="#vendors"
        class={`font-medium transition-colors drop-shadow-md ${isScrolled ? "text-gray-800 hover:text-[var(--primary)]" : "text-white hover:text-[var(--primary)]"}`}
        >Vendors</a
      >
      <a
        href="#contact"
        class="bg-[var(--primary)] text-white px-6 py-2 rounded-full font-semibold hover:bg-[var(--secondary)] transition-colors shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
      >
        Get a Quote
      </a>
    </div>
  </div>
</nav>
